## Esercizi di compito su numpy per il 19-11-2021

In [2]:
import numpy as np

#### Esercizio 1
Creare una matrice fatta scacchiera 8x8 alternando 0 e 1 (la prima cella è uno 0) 

In [17]:
mat = np.zeros((8,8), dtype=int)
#array delle posizioni dispari
indici = np.array([[i,j] for i in range(8) for j in range(8) if(i+j)%2==1])
indici

array([[0, 1],
       [0, 3],
       [0, 5],
       [0, 7],
       [1, 0],
       [1, 2],
       [1, 4],
       [1, 6],
       [2, 1],
       [2, 3],
       [2, 5],
       [2, 7],
       [3, 0],
       [3, 2],
       [3, 4],
       [3, 6],
       [4, 1],
       [4, 3],
       [4, 5],
       [4, 7],
       [5, 0],
       [5, 2],
       [5, 4],
       [5, 6],
       [6, 1],
       [6, 3],
       [6, 5],
       [6, 7],
       [7, 0],
       [7, 2],
       [7, 4],
       [7, 6]])

In [24]:
#indici.T scambia le righe con le colonne
mat[indici.T[0], indici.T[1]] = 1
mat
#MODO 2
#mat[::2, significa prendi tutto di due in due]
mat_2 = np.ones((8,8), dtype=int)
mat_2[::2,::2] = 0
mat_2[1::2,1::2] = 0
mat_2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Esercizio 2
Considerando l'array: Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generare un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]].

In [15]:
Z = np.arange(1,15)
R = np.array([Z[n:n+4] for n in range(Z.size-3)])
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### Esercizio 3
Usando la funzione numpy.random.normal(mean, dev, shape) generare un ndarray che contenga la stima dell'altezza degli alunni della classe. L'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in cm nel modo più realistico possibile.

In [64]:
np.random.normal(loc=172, scale=10, size=15)

array([161.36022476, 167.21031538, 167.96570169, 168.19552838,
       169.29300041, 159.25733816, 152.64912715, 153.07506947,
       168.00026206, 180.19729109, 159.98513264, 171.56990326,
       162.00498414, 181.12615096, 157.64912878])

#### Esercizio 4
 Creare una matrice fatta come un bersaglio 10x10, le cornici concentriche hanno valori crescenti verso il centro (quella più esterna ha valori = 1)

In [30]:
s = 20
mat_4 =  np.ones((s,s), dtype=int)
for n in range(1,s+1):
    mat_4[n-1:-n+1,n-1:-n+1] = n
print(mat_4)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  1]
 [ 1  2  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  2  1]
 [ 1  2  3  4  4  4  4  4  4  4  4  4  4  4  4  4  4  3  2  1]
 [ 1  2  3  4  5  5  5  5  5  5  5  5  5  5  5  5  4  3  2  1]
 [ 1  2  3  4  5  6  6  6  6  6  6  6  6  6  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  7  7  7  7  7  7  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  8  8  8  8  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9  9  9  9  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9 10 10  9  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9 10 10  9  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9  9  9  9  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  8  8  8  8  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  7  7  7  7  7  7  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  6  6  6  6  6  6  6  6  6  5  4  3  2  1]
 [ 1  2  3  4  5  5  5  5  5  5  5  5  5  5  5  5  4  3

### Piccola parentesi di statistica
Vediamo alcuni concetti che ci possono servire:
* La **media dei valori**, che in numpy si calcola così: `np.average(nome_array)`
* La **deviazione standard** che è un parametro che che misura quanto i valori sono concentrati attorno alla media. 
    Sarebbe il 68% dell'area sotto la Gaussiana e si calcola facendo *la radice quadrata della differenza tra la
    media dei quadrati e la media al quadrato*:
    
    ` m_2 = 1/n(x_1²+x_2²+...+x_n²) `
    
    `dev_std = sqrt(m_2-m²)`
* La **varianza** che è il quadrato della deviazione standard:
    ``v=(m_2-m²)``

In [38]:
altezze = np.array([180,171,182,175,171,177,175,179,174,185,185,190,176])
#in numpy il valore medio si calcola così:
np.average(altezze)
dev_std = np.std(altezze)
np.random.normal(loc=altezze, scale=dev_std)

array([173.92193538, 176.65961486, 175.87668401, 171.23515183,
       175.95114878, 175.40802394, 179.51417493, 181.36022852,
       175.58478509, 179.13980539, 185.00713362, 189.98978263,
       173.31077142])