In [1]:
import numpy as np

In [3]:
#creiamo un arrat
a = np.array([1,2,3,7,30])
a

array([ 1,  2,  3,  7, 30])

In [10]:
#se voglio cambiare gli array e inserire un valore costante si fa
a[...] = 5
a
a = np.array([1,2,3,7,30])

In [11]:
"""se si indicizza gli array come in python, non si creano delle copie, ma è una view di a"""
#Per indicizzare l'array
b = a[1:4]
b[...] = 99


In [12]:
b

array([99, 99, 99])

In [13]:
a

array([ 1, 99, 99, 99, 30])

In [16]:
#per capire se b è una view di a si può fare
b.base is a

True

In [26]:
#se però facciamo così c diventa una copia di a
c = a
c.base is a

False

In [27]:
#esiste un'altra indicizzazione che si chiama fancy indexing che invece crea delle copie
#e si può realizzare in due modi.

a = np.array([1,2,3,7,30])
a


array([ 1,  2,  3,  7, 30])

In [32]:
#MODO 1, indicizzare tramite booleani:
b = a[[True, False, True, False, False]]
#Prende solamente quelli con True
b[...] = 5

#b in questo caso è una copia
b.base is a

False

In [41]:
#Esempio
#Abbiamo due lanci di un dado
dado_Alice= np.random.randint(1,7,10)
dado_Bob = np.random.randint(1,7,10)
print(dado_Alice)
print(dado_Bob)

[2 3 6 6 1 5 3 2 1 1]
[2 5 6 2 2 6 4 4 5 1]


In [43]:
#Alice vince se il suo dado è il maggiore di quello di Bob
punteggi_vittoria_Alice = dado_Alice[dado_Alice > dado_Bob]

In [44]:
punteggi_vittoria_Alice.base is dado_Alice

False

In [45]:
#MODO 2, indicizzazione tramite lista di indici
a = np.array([1,2,3,7,30])
a

array([ 1,  2,  3,  7, 30])

In [49]:
b = a[[1,4,3]]
b

array([ 2, 30,  7])

In [50]:
b.base is a 

False

In [53]:
#Proviamo a fare qualcosa con gli array bidimensionali
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
#indicizzazione classica
mat[2][0]

#indicizzazione numpy
mat[2,0]
#stampare colonne si fa così
terza_colonna = mat[:,2]
terza_colonna

array([3, 6, 9])

In [62]:
terza_colonna[...] = 11
terza_colonna.base is mat

True

In [67]:
mat = np.random.randint(0,2,size=(10,10))
print(mat)
#Voglio il bordo pieno  di 0

[[0 0 1 1 1 1 1 0 1 0]
 [1 1 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 1 0 1 0 1]
 [1 1 0 1 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 1 0 0]
 [0 1 1 0 0 1 1 0 0 1]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 0 0 0 1 0 1 0 0]
 [1 0 0 0 1 0 0 1 1 0]
 [0 1 0 1 0 0 0 0 1 0]]


In [74]:
mat[[0,9],:] = 0
mat[:,[0,9]] = 0
print(mat)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1 0 0]
 [0 0 0 1 0 1 0 1 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 1 0 1 0 0]
 [0 1 1 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [81]:
mat[[0,9],:] = np.random.randint(3,9,(2,10))
mat[:,[0,9]] = np.random.randint(3,9,(10,2))
print(mat)

[[4 7 8 3 7 8 3 7 5 7]
 [6 1 0 1 0 1 0 1 0 6]
 [8 0 0 1 0 1 0 1 0 4]
 [8 1 0 1 0 0 0 0 0 8]
 [4 0 1 1 0 1 0 1 0 8]
 [6 1 1 0 0 1 1 0 0 4]
 [3 0 0 1 1 0 0 0 0 8]
 [5 0 0 0 0 1 0 1 0 3]
 [5 0 0 0 1 0 0 1 1 6]
 [4 5 7 3 3 4 6 7 6 4]]
