In [1]:
import numpy as np

Vediamo il concetto di **Broadcast**.
Il broadcast continua in fare un'operazioni su tutti gli elementi dell'array numpy.
Vediamo degli *esempi*:

In [2]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [6]:
#NB nel caso non si volesse calcolare l'altra dimensione basta dare -1 (vuol dire che la calcola lui)
b = a.reshape((4,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
c = np.ones(3)*100
c

array([100., 100., 100.])

In [11]:
#fa la somma riga per riga. L'array monodimensionale deve avere la stesso dimensione del numero di colonne.
b+c

array([[100., 101., 102.],
       [103., 104., 105.],
       [106., 107., 108.],
       [109., 110., 111.]])

In [17]:
#Esistono degli algoritmi che generano degli identicativi univoci, ovvero praticamente sono sempre diverse e si 
#generano con delle funzioni di hash


### aereoporto
C'è uno scanner in aereoporto dove si misura la temperatura di 200.000 passeggeri. L'array contiene le temperatura del 1 gennaio 2020, l'array identiifcativi contiene la lista di numeri identificativi.

In [2]:
n_passeggeri = 2000000
temperature = np.random.normal(36.5, 0.25, n_passeggeri)
#identificativi = np.array([str(uuid.uuid4()) for _ in range(n_passeggeri)])
#identificativi

##### NB in python per ciclare sui valori di due array, possiamo usare zip come se fosse enumerate dei dizionari.

In questo esercizio dobbiamo:
1. verificare quanti hanno la temperatura > 37.5
2. sapere chi sono ad avere la temperatura > 37.5

In [41]:
#1.
np.count_nonzero(temperature>37.5)

3

In [42]:
#2
#identificativi(temperature>37.5)

#### --------------------------------------------------------------------
Per poter vedere la differenza tra python e numpy possiamo usare i **comandi magici** di jupyter.
Sono dei comandi che verificano quanto tempo impiega.
`%%timeit` calcola tante volte il tempo, e scrive il tempo totale, la deviazione standard, ... )

In [49]:
%%timeit
contatore = 0
for t in temperature:
    if t > 37.5:
        contatore+=1

59.6 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
%%timeit
np.count_nonzero(temperature>37.5)

2.06 ms ± 346 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Braccio robotico
Un braccio robotico industriale libero di muoversi avanti e indietro lungo una rotaia è impazzito.
Ogni secondo si muove scegliendo a casa tra due possibili movimenti: 1cm in avanti, oppure 1cm indietro. Non è possibile togliere la corrente al robot senza bloccare tutto lo stabilimento, quindi bisogna attendere lo spegnimento che si effettua tutti i finesettimana e oggi purtroppo è lunedì! Il nostro responsabile ci chiede di simulare lo spostamento totale che il rovot avrà effettuato dopo 5 interi giorni di pazzia. Il robot è partito dalla posizione centrale della rotiaia avente coordinata 0cm.

In [39]:
#in numpy
print(f"il robot si sposta verso destra di {np.cumsum(np.random.choice([1, -1], 60*60*24*5))[-1]} cm")


il robot si sposta verso destra di 828 cm


#### le classi
Consideriamo mille classi da 25 alunni ciascuna: per ognuna di esse simuliamo il giorno di nascita di ciascun 
alunno estraendo un numero a caso tra 0 e 364 inclusi (i giorni dell'anno non bisestile sono 365): 
calcolare in quante delle mille classi ci sono almeno due alunni nati lo stesso giorno.


In [14]:
##### in numpy
n_classi= 1000
n_alunni =25
n_persone = 0
for _ in range (n_classi):
    if(np.count_nonzero(np.unique(np.random.randint(0,365,n_alunni))) != n_alunni):
        n_persone+=1
print(n_persone)


597


#### ESERCIZIO 3
Dato un array monodimensionale di numeri, trovare la posizione di tutti i massimi locali. Ad esempio, dato l'array a = [0, 2, 1, 1, 3, 2], 2 e 3 sono massimi locali rispettivamente nelle posizioni 1 e 4.


In [33]:
#numpy 
arr_a = np.array([0,2,1,55,48, 54])
arr_a = [a for a in range(1,arr_a.size-1) if arr_a[a] > arr_a[a-1] and arr_a[a] > arr_a[a+1]]
arr_a

[1, 3]

In [22]:
#python
list_a = [0,2,1,45,3,2]
list_c = []
for a in range(1, len(list_a)-1):
    if(list_a[a] > list_a[a+1]):
        list_c.append(list_a[a])
print(list_c)

[2, 45, 3]


#### Esercizio 4
Dato un array monodimensionale di numeri interi compresi tra 0 e 9, generato casualmente, trovare le posizioni dell'array in cui compare la sequenza di numeri [1, 2, 3].

In [34]:
#numpy
array_es4 = np.random.randint(0,9, 10000)

arr_indici_uguali = np.array([(a,a+1,a+2) for a in range(array_es4.size-2) if (array_es4[a:a+3] == np.array([1,2,3])).all()])
arr_indici_uguali

array([[ 352,  353,  354],
       [ 426,  427,  428],
       [ 477,  478,  479],
       [ 483,  484,  485],
       [ 935,  936,  937],
       [1994, 1995, 1996],
       [2395, 2396, 2397],
       [3007, 3008, 3009],
       [4046, 4047, 4048],
       [4689, 4690, 4691],
       [5358, 5359, 5360],
       [5639, 5640, 5641],
       [6260, 6261, 6262],
       [7010, 7011, 7012],
       [7247, 7248, 7249],
       [7834, 7835, 7836],
       [9446, 9447, 9448],
       [9499, 9500, 9501],
       [9684, 9685, 9686]])

In [46]:
array_e = np.random.randint(0,9, 2000)
array_e

array([5, 6, 3, ..., 5, 0, 1])

In [49]:
array_con = np.logical_and(np.logical_and(array_e == 1, np.roll(array_e, -1) == 2), 
               np.roll(array_e, -2) ==3)
np.arange(2000)[array_con]

array([280, 348])

In [168]:
#python
import random

lista_Es4 = []
lista_indici_uguali = []
for _ in range(1000):
    lista_Es4.append(random.randint(0,9))
for a in range(len(lista_Es4)-2):
    if lista_Es4[a:a+3] == [1,2,3]:
        lista_indici_uguali.append((a,a+1,a+2))
lista_indici_uguali

[(939, 940, 941)]

#### Esercizio 5
Sul territorio comunale sono installate tre centraline per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta le centraline vanno in uno stato di errore per cui la misurazione delle PM10 fallisce ed il dato corrispondente riporta il valore 9999.9 all'interno dell'array delle misurazioni. Inoltre, per motivi sconosciuti, talvolta le centraline riportano il valore -1. Statisticamente si è visto che il primo errore ha una frequenza dello 0.2% mentre il secondo del 0.1%
Creare una matrice avente 3 colonne e le righe contenente i dati di tutte le centraline registrati nelle 24 ore (si registra il dato ogni minuto)
Eliminare tutte le righe della matrice in cui vi sia almeno una misura errata o una misura di origine sconosciuta

In [182]:
#numpy
num_minuti = 24*60
valore_0_2_non_percentuale = 0.2/100
valore_0_1_non_percentuale = 0.1/100

def num_random(a):
    val = np.random.random()
    if val < valore_0_1_non_percentuale:
        return 9999
    elif val < valore_0_2_non_percentuale:
        return -1
    else:
        return np.random.randint(0,40)


num_random_v = np.vectorize(num_random)

matrice = np.ones((num_minuti, 3))

matrice = num_random_v(matrice)

risultati_validi = matrice[[[matrice[a][i] != 9999.9 and matrice[a][i] !=-1 for i in range(3)] for a in range(24*60)]]
risultati_validi

array([29, 30, 22, ..., 28, 31, 11])

In [36]:
#python
import random

# generatore di numeri random
def num_random():
    val = random.random()
    if val < valore_0_1_non_percentuale:
        return 9999.9
    elif val < valore_0_2_non_percentuale:
        return -1
    else:
        return random.randint(0,40)
    

# creazione matrice
matrice = []
for _ in range(num_minuti):
    
    riga = []
    
    for _ in range(3):
        riga.append(num_random())
        
    matrice.append(riga)
    
print(matrice)

# trovare gli array da eliminare
array_indici_da_eliminare = []
for i, val in enumerate(matrice):
    if -1 in val or 9999.9 in val:
        matrice.pop(i)

print("\n\n")
print(matrice)
            

NameError: name 'num_minuti' is not defined

Per quanto riguarda l'esercizio dei compleanni, se volessimo calcolare **matematicamente** la probabilità che tutti abbiano il compleanno in un giorno diverso dovremmo fare:
`P_comp_differente = 365/365 * 364/365 * ... n volte` → quindi se definiamo `n` come il numero di persone in una classe, la formula è : `P_comp_differente = 364/365 * 365/365 * (365-n+1)/365`

Di conseguenza volessimo sapere la probabilità che in una classe ci siano 2 o più persone nate nello stesso giorno è:
`P_comp_uguale = 1 - P_comp_differente`