In [1]:
import numpy as np

In [3]:
#Come passare da liste ad array numpy, utilizzando il costruttore
lista = [1,2,3,4,5,6]

lista_array = np.array(lista)
print(lista_array)

[1 2 3 4 5 6]


Si può vedere che sono oggetti differenti

In [8]:
lista_array

array([1, 2, 3, 4, 5, 6])

In [9]:
lista

[1, 2, 3, 4, 5, 6]

In [16]:
#fa un array di n dimensioni(prende il nome di shape ed è caratterizzata da un tupla), di n tipi
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones((5,10), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
#con la size si ha la dimensione dell'array che restituisce
np.random.uniform(low=5, high=8, size=10)

array([6.34812148, 7.70572689, 5.80187997, 6.96680989, 7.76363456,
       5.62445074, 7.9837914 , 6.55081626, 7.78485869, 5.20183564])

In [31]:
#in numpy può tirare a sorte una distruzione gaussiana o normale
#la gaussiana è centrata sullo 0 e si può cambiare con loc e con scale
#che dice quanto è larga o stretta la gaussiana
np.random.normal(loc=10, scale=1, size=10)

array([ 9.05878944,  8.58650424,  9.94833842,  7.86588057,  9.17651528,
       10.94451291, 10.62989292,  9.80634793, 11.69999154,  8.31325657])

In [37]:
#per tirare a sorte numeri interi (sia low che high sono inclusi). Sono distribuiti in maniera uniforme
np.random.randint(low=1, high=7, size=10)

array([6, 6, 2, 5, 5, 2, 5, 1, 5, 6])

In [41]:
#c'è un'altra funzioe random, che permette di scegliere casualmente valori presenti in una lista o array
np.random.choice(["Testa", "Croce"], size=10)

array(['Croce', 'Croce', 'Testa', 'Croce', 'Croce', 'Testa', 'Croce',
       'Testa', 'Testa', 'Croce'], dtype='<U5')

## NB
le dimensioni spaziali che servono per rappresentare gli array si utilizzano degli assi standard:
- l'array 1D si chiama asse0 (axis0)
- l'array 2D ha l'asse 0 quello delle righe e l'asse 1 quello delle colonne
- l'array 3D è uguale al 2D con l'asse 2 che è la profondità.
----------------------------------

In [49]:
#shape di un array 2D
matrice = np.random.uniform(size=(4,5))
np.shape(matrice)

(4, 5)

In [50]:
#shape di un array 1D
vettore = np.array([1,2,3,4,5])
np.shape(vettore)

(5,)

In [53]:
#serve per trasformare array 2D, in array 1D
matrice1 = np.ravel(matrice)
print(matrice1)

[0.47554774 0.32171455 0.59776217 0.13881394 0.7163944  0.34899172
 0.8007524  0.88639373 0.00481521 0.73808497 0.26358035 0.92309497
 0.37535401 0.66567328 0.23438801 0.66400632 0.88465112 0.47242373
 0.35283068 0.21685708]


In [57]:
#per accedere agli array si deve fare:

"""Nel caso sia 1D"""
print(vettore[2])

"""Nel caso sia 2D"""
print(matrice[2][3])


3
0.6656732782581452


In [59]:
#se scriviamo ciò e stampiamo
matrice1[0] = 111111.1
print(matrice)
#cambia anche matrice. Puntano allo stesso oggetto.

[[1.11111100e+05 3.21714554e-01 5.97762166e-01 1.38813945e-01
  7.16394402e-01]
 [3.48991719e-01 8.00752400e-01 8.86393725e-01 4.81521487e-03
  7.38084970e-01]
 [2.63580350e-01 9.23094966e-01 3.75354015e-01 6.65673278e-01
  2.34388011e-01]
 [6.64006325e-01 8.84651120e-01 4.72423727e-01 3.52830681e-01
  2.16857079e-01]]


In [65]:
#si può inoltre cambiare la forma delgi array con la funzione .reshape
matrice.reshape((10,2))
#gli elementi totali devono essere sempre uguali, in questo caso sempre 20 elementi

array([[1.11111100e+05, 3.21714554e-01],
       [5.97762166e-01, 1.38813945e-01],
       [7.16394402e-01, 3.48991719e-01],
       [8.00752400e-01, 8.86393725e-01],
       [4.81521487e-03, 7.38084970e-01],
       [2.63580350e-01, 9.23094966e-01],
       [3.75354015e-01, 6.65673278e-01],
       [2.34388011e-01, 6.64006325e-01],
       [8.84651120e-01, 4.72423727e-01],
       [3.52830681e-01, 2.16857079e-01]])

In [67]:
#creiamo una matrice trasposta (ovvero una matrice che inverte righe e colonne)
np.transpose(matrice)

array([[1.11111100e+05, 3.48991719e-01, 2.63580350e-01, 6.64006325e-01],
       [3.21714554e-01, 8.00752400e-01, 9.23094966e-01, 8.84651120e-01],
       [5.97762166e-01, 8.86393725e-01, 3.75354015e-01, 4.72423727e-01],
       [1.38813945e-01, 4.81521487e-03, 6.65673278e-01, 3.52830681e-01],
       [7.16394402e-01, 7.38084970e-01, 2.34388011e-01, 2.16857079e-01]])

--------------------------------
#### Esempio
Abbiamo un dado a 6 facce e facciamo 10.000 lanci.
1. Vogliamo vedere quanti sono i 6 usciti
2. Quante volte c'è un numero maggiore di 3
3. Il numero di volte che la somma di due numeri usciti da due dadi sia 8

In [76]:
#simuliamo i lanci
lanci_dado1 = np.random.randint(1,7, 10000)
print(lanci_dado)

lanci_dado2 = np.random.randint(1,7, 10000)
print(lanci_dado)


[5 6 3 ... 1 4 1]
[5 6 3 ... 1 4 1]


In [71]:
#proviamo a vedere quali sono i 6
lanci_dado == 6

array([False,  True, False, ..., False, False, False])

In [74]:
#contiamo gli 1
np.count_nonzero(lanci_dado==6)/10000
#al tendere dei numeri di lancio ad infinito questo numero sarà sempre più vicino a 1./6

0.1696

In [75]:
#vediamo il punto 2
np.count_nonzero(lanci_dado >= 4)/10000

0.5021

In [79]:
#vediamo il punto 3
np.count_nonzero(lanci_dado1 + lanci_dado2 == 8)/10000
#(lanci_dado1 + lanci_dado2) somma elemento per elemento

0.1484

In [37]:
import numpy as np

In [43]:
np.random.randint(2,3)

2