In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])

In [6]:
#Qualunque operazione che faccio lo fa elemento per elemento. NB gli array devono essere lunghi uguali
"""AD ESEMPIO"""
print(a**b)
print(a*b)
print(a+b**a)
print(a%2)

[ 1  4  9 16]
[2 4 6 8]
[ 3  6 11 20]
[1 0 1 0]


### Vediamo se un numero è primo oppure no
1. **Metodo classico** con il ciclo for
    La grande limitazione di questo metodo è che posso passargli un solo valore, non un array

In [12]:
def isPrime(n):
    for i in range(2, int(np.sqrt(n))+1):
        if n%i == 0:
            return False
    return True

isPrime(23)

True

2. **Metodo numpy** con le funzioni numpy. In questo modo dalla funzione python ottengo una funzione vettorizzata

In [16]:
c = np.arange(2,90)

isPrime_v = np.vectorize(isPrime)
isPrime_v(c)

array([ True,  True, False,  True, False,  True, False, False, False,
        True, False,  True, False, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False,  True, False, False, False,  True, False,  True,
       False, False, False, False, False,  True, False, False, False,
        True, False, False, False, False, False,  True])

In [17]:
#Lista di numeri primi
c[isPrime_v(c)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89])

In [18]:
#NB in numpy ci sono alcune funzioni ad esempio il PI GRECO
np.pi

3.141592653589793

In [ ]:
"""
COMPITO
Dato un esempio di reference trovato in rete, crearne una nostra. Ovvero con funzione di numpy dire cosa fa e 
fare un esempio.
"""