In [4]:
import numpy as np

1) Creare una funzione che inverta un ndarray monodimensionale, ovvero crei un array monodimensionale con gli stessi elementi dell'array di partenza in ordine inverso.

In [5]:
#primo modo
arr1 = np.array([1,2,3,4,5])

def inverti_array(array_da_invertire):
    return np.array([array_da_invertire[-a] for a in range(1,len(array_da_invertire)+1)])

print(inverti_array(arr1))
    

[5 4 3 2 1]


In [9]:
#secondo modo
arr1[::-1]

array([5, 4, 3, 2, 1])

In [11]:
#terzo modo
np.flip(arr1)

array([5, 4, 3, 2, 1])

2) Generare un array Numpy che contenga le posizioni dei primi 100 numeri primi all'interno dei numeri naturali

In [6]:
#primo modo
def crea_array_numeri_primi(n_primi):
    a = 2
    arr_n_primi = []
    while len(arr_n_primi) != n_primi:
        ePrimo = True
        for num in arr_n_primi:
            if a%num == 0: 
                ePrimo = False
                num = arr_n_primi[-1]
        if ePrimo:arr_n_primi.append(a)
        a+=1
    return np.array(arr_n_primi)

print(crea_array_numeri_primi(100))
            

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
 467 479 487 491 499 503 509 521 523 541]


In [13]:
#secondo modo
def isprime(n):
    ret = True
    for i in range(2,int(n**0.5)+1):
        if n%i==0:
            ret = False
            break
    return ret
#Vettorizzare significa che analizza ogni elemento dell'array numpy e crea un array di True e False
isprime_v = np.vectorize(isprime)
natural_n = np.arange(2,1000)
#Praticamente in questo ritorna gli elementi solo con valore True
(natural_n[isprime_v(natural_n)]+1)[:100]

array([  3,   4,   6,   8,  12,  14,  18,  20,  24,  30,  32,  38,  42,
        44,  48,  54,  60,  62,  68,  72,  74,  80,  84,  90,  98, 102,
       104, 108, 110, 114, 128, 132, 138, 140, 150, 152, 158, 164, 168,
       174, 180, 182, 192, 194, 198, 200, 212, 224, 228, 230, 234, 240,
       242, 252, 258, 264, 270, 272, 278, 282, 284, 294, 308, 312, 314,
       318, 332, 338, 348, 350, 354, 360, 368, 374, 380, 384, 390, 398,
       402, 410, 420, 422, 432, 434, 440, 444, 450, 458, 462, 464, 468,
       480, 488, 492, 500, 504, 510, 522, 524, 542])

3) Generare un array Numpy contenente i primi 10 numeri di Fibonacci

In [17]:
#primo modo
def crea_seq_fibonacci(n_numeri):
    array_seq_fibonacci = [1,1]
    for _ in range(2,n_numeri+1):
        array_seq_fibonacci.append((array_seq_fibonacci[-1]+array_seq_fibonacci[-2]))
    return np.array(array_seq_fibonacci[1:])
                                   
print(crea_seq_fibonacci(10))

[ 1  2  3  5  8 13 21 34 55 89]


In [15]:
#secondo modo
n = 11
start = np.ones(11,dtype=int)
for i in range(2,n):
    start[i]=start[i-1]+start[i-2]
start[1:]

array([ 1,  2,  3,  5,  8, 13, 21, 34, 55, 89])